name: 'Create Release'
description: 'Create a GitHub Release'
inputs:
  token:
    name: 'Tag name'
    required: true
  tag_name:
    name: 'Tag name'
    required: true
  release_name:
    name: 'Release name'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
